name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: verify secrets
        run: echo "${{ secrets.DOCKER_USERNAME }} and ${{ secrets.DOCKER_PASSWORD }}"
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build Spring Boot application
        run: mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GIT_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build Docker image
        run: docker build -t hdk-auth-api .

      - name: Tag Docker image with commit hash
        run: docker tag hdk-auth-api hdk-auth-api:${{ github.sha }}

      - name: Push Docker image
        run: docker push hdk-auth-api:${{ github.sha }}

      - name: Get Docker image new version
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
