name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: verify secrets
        run: echo "${{ secrets.DOCKER_USERNAME }} and ${{ secrets.DOCKER_PASSWORD }}"

      - name: verify hash
        run: echo "$${{ github.sha }} and ${{ github.ref }}"
        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build Spring Boot application
        run: mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hdk-auth-api .

      - name: Tag Docker image with branch name
        run: docker tag hdk-auth-api hdk-auth-api:latest

      - name: Push Docker image
        run: docker push creito/hdk-auth-api:${{ github.sha }} ${{ github.ref }}

      - name: Get Git commit hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
